// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using SkyworxCredit.Infrastructure.Data;

#nullable disable

namespace SkyworxCredit.Infrastructure.Migrations
{
    [DbContext(typeof(CreditDbContext))]
    partial class CreditDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("SkyworxCredit.Domain.Entities.PengajuanKredit", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<decimal>("Angsuran")
                        .HasColumnType("numeric")
                        .HasColumnName("angsuran");

                    b.Property<decimal>("Bunga")
                        .HasColumnType("decimal(5,2)")
                        .HasColumnName("bunga");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<decimal>("Plafon")
                        .HasColumnType("numeric")
                        .HasColumnName("plafon");

                    b.Property<int>("Tenor")
                        .HasColumnType("integer")
                        .HasColumnName("tenor");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.HasIndex("Plafon");

                    b.HasIndex("Tenor");

                    b.ToTable("pengajuan_kredit", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
